//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naos.Bootstrapper
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages
    {
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Looks up a localized string similar to Application started..
        /// </summary>
        internal static string Application_Started {
            get
            {
                return "Application started.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find required &apos;Content-Disposition&apos; header field in MIME multipart body part..
        /// </summary>
        internal static string Exception_ContentDispositionHeaderRequired {
            get
            {
                return "Did not find required 'Content-Disposition' header field in MIME multipart body part.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling UseCors requires your hosting settings to be configured with the cors property and that at minimum its origins property contain at least one origin value..
        /// </summary>
        internal static string Exception_UseCors_NoSettingsProvided {
            get
            {
                return "Calling UseCors requires your hosting settings to be configured with the cors property and that at minimum its origins property contain at least one origin value.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load certificate specified by JwtAuthenticationSettings..
        /// </summary>
        internal static string Exception_UseJwtAuthentication_CertificateNotFound {
            get
            {
                return "Unable to load certificate specified by JwtAuthenticationSettings.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JwtAuthenticationSettings may only specify zero or one certificates to load - either a storeCertificate, relativeFileCertificate, or neither (for unencrypted JWT tokens), but not both..
        /// </summary>
        internal static string Exception_UseJwtAuthentication_MultipleOptionsProvided {
            get
            {
                return "JwtAuthenticationSettings may only specify zero or one certificates to load - either a storeCertificate, relativeFileCertificate, or neither (for unencrypted JWT tokens), but not both.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A private key could not be read from the certificate specified by JwtAuthenticationSettings..
        /// </summary>
        internal static string Exception_UseJwtAuthentication_NoPrivateKey {
            get
            {
                return "A private key could not be read from the certificate specified by JwtAuthenticationSettings.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load JwtAuthenticationSettings from the container; please ensure that the file exists in your configuration and that UseSettingsContainerInitializer has been called or explicitly supply the value when calling UseJwtAuthentication..
        /// </summary>
        internal static string Exception_UseJwtAuthentication_NoSettingsProvided {
            get
            {
                return "Could not load JwtAuthenticationSettings from the container; please ensure that the file exists in your configuration and that UseSettingsContainerInitializer has been called or explicitly supply the value when calling UseJwtAuthentication.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate assembly for {0} when attempting to load settings from configuration; to fix make sure you have a type named {0} and add typeof({0}).Assembly to the list of parameters supplied to UseSettingsContainerInitializer if the assembly is not already loaded into memory already by the main process..
        /// </summary>
        internal static string Exception_UseSettingsContainerInitializer_NoType {
            get
            {
                return "Could not locate assembly for {0} when attempting to load settings from configuration; to fix make sure you have a type named {0} and add typeof({0}).Assembly to the list of parameters supplied to UseSettingsContainerInitializer if the assembly is not already loaded into memory already by the main process.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string Exception_ValueMustBeGreaterThanOrEqualTo {
            get
            {
                return "Value must be greater than or equal to {0}.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to quit..
        /// </summary>
        internal static string Quit {
            get
            {
                return "Press any key to quit.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server is running on: {0}.
        /// </summary>
        internal static string Web_Server_Running {
            get
            {
                return "Web server is running on: {0}";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server was terminated by a user..
        /// </summary>
        internal static string Web_Server_Terminated {
            get
            {
                return "Web server was terminated by a user.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load certificate specified by JwtOAuthServerSettings allowedClients with Id = &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_JwtAccessTokenFormat_CertificateNotFound {
            get
            {
                return "Unable to load certificate specified by JwtOAuthServerSettings allowedClients with Id = '{0}'.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid audience (client id) on this server.
        /// </summary>
        internal static string Exception_JwtAccessTokenFormat_InvalidClientId {
            get
            {
                return "'{0}' is not a valid audience (client id) on this server";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JwtOAuthServerSettings allowedClients with Id &apos;{0}&apos; can only specify zero or one certificates to load - either a storeCertificate, relativeFileCertificate, or neither (for unencrypted JWT tokens), but not both..
        /// </summary>
        internal static string Exception_JwtAccessTokenFormat_MultipleCertificateOptionsProvided {
            get
            {
                return "JwtOAuthServerSettings allowedClients with Id '{0}' can only specify zero or one certificates to load - either a storeCertificate, relativeFileCertificate, or neither (for unencrypted JWT tokens), but not both.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication ticket does not have an audience (client id) property.
        /// </summary>
        internal static string Exception_JwtAccessTokenFormat_NoAudience {
            get
            {
                return "Authentication ticket does not have an audience (client id) property";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client_id &apos;{0}&apos;..
        /// </summary>
        internal static string OAuthError_InvalidClientId {
            get
            {
                return "Invalid client_id '{0}'.";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in user..
        /// </summary>
        internal static string OAuthError_InvalidGrant {
            get
            {
                return "Unable to sign in user.";
            }
        }
    }
}
