// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ConsoleAbstractionBaseStandin.cs" company="Naos Project">
//   Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in 'Naos.Bootstrapper.Recipes.Core.Console' source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using OBeautifulCode.Representation.System;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace Naos.Bootstrapper
{
    /// <summary>
    /// Compile only, not included in package.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("Naos.Bootstrapper", "See package version number")]
    public abstract class ConsoleAbstractionBaseStandin
    {
        /// <summary>
        /// Gets or sets the exception type representations to only print message.
        /// </summary>
        /// <value>The exception type representations to only print message.</value>
        public static TypeRepresentation[] ExceptionTypeRepresentationsToOnlyPrintMessage { get; set; }
    }
}