// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Startup.cs" company="Naos Project">
//   Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in 'Naos.Bootstrapper.Recipes.Hangfire.Console' source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Bootstrapper.Recipes.Spritely.Api
{
    /// <summary>
    /// Example implementation to get compiling.
    /// </summary>
    public partial class Startup
    {
    }
}
