// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ValidatedNotNullAttribute.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Validation source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Validation.Recipes
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Attribute that avoids false positives of Code Analysis rule CA1062.
    /// </summary>
    /// <remarks>
    /// See <a href="http://esmithy.net/2011/03/15/suppressing-ca1062/" />.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Parameter)]
#if !OBeautifulCodeValidationRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Validation", "See package version number")]
    internal
#else
    public
#endif
        sealed class ValidatedNotNullAttribute : Attribute
    {
    }
}
